apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: 968225077300.dkr.ecr.us-east-1.amazonaws.com/workshop-backend
  newTag: e83eec7
- name: 968225077300.dkr.ecr.us-east-1.amazonaws.com/workshop-frontend
  newTag: 92a54b9
